AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - com.amazon::LambdaQuarkus
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  Proxy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: target/quarkus-api-gw-event-handler-1.0-SNAPSHOT-runner.jar
      MemorySize: 256
      Timeout: 15
      Events:
        PostBook:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /book
            Method: POST
        GetBookById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /book/{id}
            Method: GET
        PutBookById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /book/{id}
            Method: PUT

Outputs:
  ApiUrl:
    Description: URL of the users listing in the prod stage
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"