AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - com.amazon::LambdaQuarkus
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  LambdaQuarkusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: target/function.zip
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          # see https://quarkus.io/guides/amazon-lambda-http
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        PostBook:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /book
            Method: PUT
        GetBookById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /book/{id}
            Method: GET

Outputs:
  ApiUrl:
    Description: URL of the users listing in the prod stage
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"